# Generated by Django 4.2 on 2023-06-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Adminapp", "0002_userinfo"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userinfo",
            table="Userinfo",
        ),
    ]
