# Generated by Django 4.2 on 2023-06-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Adminapp", "0003_alter_userinfo_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paymentmaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cardno", models.CharField(max_length=20)),
                ("cvv", models.CharField(max_length=4)),
                ("expiry", models.CharField(max_length=20)),
                ("balance", models.FloatField(default=1000)),
            ],
            options={
                "db_table": "Paymentmaster",
            },
        ),
    ]
