# Generated by Django 4.2 on 2023-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Adminapp", "0004_paymentmaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="add",
            field=models.CharField(default="M.G Road Pune", max_length=50),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="phn",
            field=models.CharField(default="9876543214", max_length=10),
        ),
    ]
