# Generated by Django 4.2 on 2023-08-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Adminapp", "0005_userinfo_add_userinfo_phn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("phn", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("query", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "Query",
            },
        ),
    ]
