# Generated by Django 4.2 on 2023-08-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Adminapp", "0006_query"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="query",
            name="id",
        ),
        migrations.AlterField(
            model_name="query",
            name="Name",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
