# Generated by Django 4.2 on 2023-08-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Adminapp", "0007_remove_query_id_alter_query_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="shop_name",
            field=models.CharField(default="For Cakes sake", max_length=30),
        ),
    ]
