# Generated by Django 4.2 on 2023-09-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Adminapp", "0008_category_shop_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="add",
        ),
    ]
