# Generated by Django 4.2 on 2023-09-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Adminapp", "0010_product_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="shop_name",
        ),
    ]
