# Generated by Django 4.2 on 2023-09-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Adminapp", "0011_remove_category_shop_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="add",
            field=models.CharField(default="M.G.Road Pune", max_length=100),
            preserve_default=False,
        ),
    ]
