# Generated by Django 4.2 on 2023-06-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Adminapp", "0003_alter_userinfo_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mycart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField()),
                (
                    "cake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Adminapp.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Adminapp.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "Mycart",
            },
        ),
    ]
