# Generated by Django 4.2 on 2023-06-21 17:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Adminapp", "0004_paymentmaster"),
        ("Userapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ordermaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=1000)),
                (
                    "dateoforder",
                    models.DateField(
                        verbose_name=datetime.datetime(2023, 6, 21, 22, 58, 26, 829346)
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Adminapp.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "ordermaster",
            },
        ),
    ]
