# Generated by Django 4.2 on 2023-06-21 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Userapp", "0002_ordermaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermaster",
            name="details",
            field=models.CharField(default="Null", max_length=1000),
        ),
        migrations.AlterField(
            model_name="ordermaster",
            name="dateoforder",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 21, 23, 15, 48, 924336)
            ),
        ),
    ]
