# Generated by Django 4.2 on 2023-08-28 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Userapp", "0004_alter_ordermaster_dateoforder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermaster",
            name="dateoforder",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 29, 0, 29, 0, 519744)
            ),
        ),
    ]
