# Generated by Django 4.2 on 2023-09-03 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Userapp", "0010_alter_ordermaster_dateoforder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermaster",
            name="dateoforder",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 3, 21, 22, 6, 783903)
            ),
        ),
    ]
